name: Deploy Multi-Container Todo App via SSM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1   # change to your region

      # 3️⃣ Deploy app via SSM
      - name: Deploy via SSM
        run: |
          # Get EC2 instance ID by Name tag
          INSTANCE_ID=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=todo-server" \
            --query "Reservations[0].Instances[0].InstanceId" \
            --output text)

          echo "Deploying to EC2 instance $INSTANCE_ID via SSM..."
